language: python
# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

cache:
  - pip
  - apt

#compiler: gcc-4.8  # need c++11 support and open-mp
#dist: trusty

# safelist
branches:
  only:
  - macos_fix

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cpp-6

env:
  global:
    - OMP_NUM_THREADS=2
    - CC=gcc-6
    - CXX=g++-6
    - CPP=cpp-6
    - LD=gcc-6

python:
  - 2.7
  - 3.4
  - 3.5

# command to install dependencies
install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - gcc -v
  - gcc-6 -v
  - pip install -r pip-requirements
  - pip install .

# command to run tests
script:
  - cd tests
  - nosetests
  - cd ..
